<template>
    <v-app id="app">
        <v-card class="overflow-hidden">
            <v-app-bar
                    scroll-target="#scrolling-sheet"
                    class="gradient"
                    dark
            >
                <v-toolbar-title class="pl-12">Recipes generated by <strong>AI</strong></v-toolbar-title>

                <v-text-field
                        class="search-bar"
                        hide-details
                        prepend-icon="search"
                        single-line
                        clearable
                        autofocus
                        label="Search"
                ></v-text-field>

                <v-btn icon>
                    <v-icon>mdi-heart</v-icon>
                </v-btn>

                <v-btn icon>
                    <v-icon>face</v-icon>
                </v-btn>
            </v-app-bar>

            <v-sheet
                    id="scrolling-sheet"
                    class="overflow-y-auto theme-backround"
            >
                <!-- Sizes your content based upon application components -->
                <v-content>
                    <!-- Provides the application the proper gutter -->
                    <v-container fluid>
                        <!-- If using vue-router -->
                        <router-view></router-view>
                    </v-container>
                </v-content>
            </v-sheet>
        </v-card>

        <v-footer
                v-bind="localAttrs"
                :padless="padless"
                width="100%"
                class="GOred lighten-1"
        >
            <v-card
                    flat
                    tile
                    width="100%"
                    class="GOred lighten-1 text-center"
            >
                <v-card-text class="footer">
                    <a href="https://github.com/generated-online" style="vertical-align:top" class="pa-4" ><img src="/github.png" alt="github" width="44"></a>
                    <span class="pa-4 pr-12"><a href="https://github.com/generated-online"><strong>Github</strong></a></span>

                    <a href="" class="pa-4 pr-12" ><v-icon color="white" size="33">security</v-icon></a>
                    <span class="pa-4"><a href=""><strong>Privacy Policy</strong></a></span>
                </v-card-text>
                <v-divider/>
                <v-card-text class="white--text small-font">
                    {{ new Date().getFullYear() }} — generated.online
                </v-card-text>
            </v-card>
        </v-footer>
    </v-app>
</template>

<style>
    @media only screen and (max-width: 1200px) {
        .search-bar{
            padding-left: 5% !important;
            padding-right: 10% !important;
        }
    }
    @media only screen and (max-width: 800px) {
        /*move search bar in next line*/
    }

    .search-bar{
        padding-left: 20%;
        padding-right: 30%;
    }
    .theme-backround{
        background-color: #939ca8 !important;
    }

.gradient{
    background: linear-gradient(45deg,#F2AB27,#D94D1A);
}
.footer li {
    display: inline-block;
}
.footer {
    padding-top: 30px;
    padding-bottom: 30px;
    width: 100%;
    color: white;
    text-align: center;
    color: white;
}
.footer a:link {
    text-decoration: none;
}
.footer a {
    color: white !important;
}

#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
#nav {
  padding: 30px;
}
#nav a {
  font-weight: bold;
  color: #2c3e50;
}

#nav a.router-link-exact-active {
  color: #42b983;
}
.menu-bar {
    height: 67px !important;
    background-color: white !important;
}
.small-font {
    font-size: 0.8em  !important;
}
.normal-font {
    font-size: 1.1em  !important;
}
.large-font {
    font-size: 2em !important;
}
.red-highlight:hover {
    color: #b71c1c !important;
}
.green-highlight:hover {
    color: green !important;
}
.larger-font {
    font-size: 1.3em !important;
    line-height: 1.3em !important;
    font-weight: normal !important;
    color: #121212 !important;
}
.list {
    min-height: 28px !important;
}
.center-text {
    text-align: center !important;
}
</style>
