export default {
        emoMap: {
            'rind': 'steak',
            'speck': 'schinken',
            'haselnüsse': 'kastanie',
            "lachs": 'fisch',
            "forelle": 'fisch',
            "brasse": 'fisch',
            "karpfen": 'fisch',
            "hecht": 'fisch',
            "äpfel": 'apfel',
            "möhre": "karotte",
            "gelberübe": "karotte",
            "eigelb": "ei",
            "thymian": "kräuter",
            "oregano": "kräuter",
            "basilikum": "samen",
            "petersilie": "kräuter",
            "fleisch": "steak",
            "parmesan": "käse",
            "gorgonzola": "käse",
            "gauda": "käse",
            "emmenthaler": "käse",
            "erdnüsse": "erdnuss",
            "haselnüsse": "haselnuss",
            "manderine": "orange",
            "clementine": "orange",
            "schwammerl": "pilz",
            "champignons": "pilz",
            "eigelb": "ei",
            "eiweiß": "ei",
            "filet": "steak",
            "braten": "steak",
            "hühnchen": "juhn",
            "pute": "truthahn",
            "geflügel": "ente",
            "plätzchen": "keks",
            "gebäck": 'keks',
            "getreide": "hafer",
            "erdnüsse": "erdnuss",
            "kalb": "kuh"

        },
        // emos must be sorted by lengths for better matching
        allEmos: [
            "ei", "kuh", "eis", "lamm", "huhn", "ente", "kiwi", "mais", "pilz",
            "brot", "käse", "taco", "salz", "dose", "reis", "keks", "wein", "bier", "schinken",
            "fisch", "schaf", "samen", "hafer", "olive", "mango", "apfel", "birne",
            "chili", "gurke", "salat", "breze", "pizza", "sushi", "honig", "milch",
            "karotte", "wasser", "krabbe", "hummer", "melone", "banane", "tomate",
            "burger", "pommes", "muffin", "kuchen", "ananas", "oktopus", "garnele", "schwein", "truthan",
            "weintrauben", "zwiebel",
            "paprika", "avocado", "zitrone", "kirsche", "avocado", "karotte", "steak",
            "burrito", "spiegelei", "popcorn",
            "schinken", "karotte", "aubergine", "erdbeere", "pfirsich", "brokkoli",
            "erdnuss", "kastanie", "baguette", "sandwich", "cocktail",
            "kartoffel", "knoblauch", "blaubeere", "orange", "kokosnuss", "kartoffel",
            "croissant", "spaghetti", "reis", "schokolade",
            "tintenfisch", "pfannkuchen", "schnittlauch",
            "wassermelone", "süßkartoffel"
        ]

}