[tool.poetry]
name = "upload"
version = "0.1.0"
description = ""
authors = ["Moritz Wolf <moritz.m.wolf@tum.de>"]

[tool.poetry.dependencies]
python = "^3.6"
firebase_admin = "^4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
